name: Tests d'API avec Newman (Postman)

on:
  push:
    branches:
      - ismail
  pull_request:
    branches:
      - ismail

jobs:
  build-and-test:
    name: Test + Analyse API via Newman (Postman)
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:3000

    steps:
      - name: Checkout du repos
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Installation des dépendances
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Lancement de l'application
        run: yarn start &
      
      - name: Attente démarrage du serveur
        uses: WyriHaximus/github-action-wait-for@v2
        with:
          target: http://localhost:3000
          timeout: 60s
        
      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run rwa-api-collection.json -reporters cli,json -reporter-json-export results.json

      - name: Upload Resultats
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: results.json