name: Tests de performance avec JMeter
on:
  push:
    branches:
      - ismail
  pull_request:
    branches:
      - ismail

jobs:
  build-and-test:
    name: Test + Analyse Performance via JMeter
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:3000

    steps:
      - name: Checkout du repos
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Installation des dépendances
        run: yarn install --frozen-lockfile

      # - name: Linting
      #   run: yarn lint
    
      - name: Lancement de l'application
        run: yarn start &
    
      - name: Configuration de Java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '21'

      - name: Installation de JMeter
        run: |
            wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
            tar -xzf apache-jmeter-5.6.3.tgz
            echo "JMETER_HOME=$(pwd)/apache-jmeter-5.6.3" > $GITHUB_ENV

      - name: Exécution des tests avec JMeter
        run: $JMETER_HOME/bin/jmeter -n -t jmeter/PerformanceTestPlanMemoryThread.jmx -l results.jtl

            