name: Tests de sécurité avec ZAP

on:
  push:
    branches:
      - ismail
  pull_request:
    branches:
      - ismail

jobs:
  build-and-test:
    name: Test + Analyse Securité via ZAP
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:3000

    steps:
      - name: Checkout du repos
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Installation des dépendances
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Scan de sécurité ZAP
        uses: zaproxy/action-baseline@v0.15.0
        with:
            target: "https: /example.com"

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
            name: zap-report
            path: report.html
    